export const TERMS = {
  "夏普比率": { name:"夏普比率", english:"Sharpe Ratio", desc:"衡量投资回报与风险的比例。比率越高，每承担一单位风险得到的回报越高。通常 >1 良好，>2 优秀。", formula:"(收益率 - 无风险利率) / 标准差" },
  "最大回撤": { name:"最大回撤", english:"Max Drawdown", desc:"从最高点到最低点的最大跌幅，衡量策略最坏情况下的亏损幅度。", formula:"(波峰净值 - 波谷净值) / 波峰净值 x 100%" },
  "年化收益": { name:"年化收益", english:"Annualized Return", desc:"将总收益率换算为一年的收益率，便于不同周期策略比较。" },
  "胜率": { name:"胜率", english:"Win Rate", desc:"盈利交易次数占总交易次数的比例。高胜率不一定高收益。" },
  "盈亏比": { name:"盈亏比", english:"Profit/Loss Ratio", desc:"平均盈利金额与平均亏损金额的比值。大于 2 说明盈亏结构良好。" },
  "MACD": { name:"MACD", english:"Moving Average Convergence Divergence", desc:"指数平滑异同移动平均线，由快线(DIF)、慢线(DEA)、柱状图组成，用于判断趋势和买卖点。" },
  "RSI": { name:"RSI", english:"Relative Strength Index", desc:"相对强弱指标，衡量价格涨跌幅度。RSI > 70 超买，RSI < 30 超卖。" },
  "KDJ": { name:"KDJ", english:"Stochastic Oscillator", desc:"随机指标，由K线、D线、J线组成，用于判断超买超卖和趋势转折。" },
  "布林带": { name:"布林带", english:"Bollinger Bands", desc:"由中轨(均线)、上轨(均线+N倍标准差)、下轨(均线-N倍标准差)组成，反映价格波动范围。" },
  "均线": { name:"均线", english:"Moving Average (MA)", desc:"一定周期内收盘价的算术平均值，用于平滑价格走势，判断趋势方向。" },
  "金叉": { name:"金叉", english:"Golden Cross", desc:"短期均线上穿长期均线，通常视为买入信号。" },
  "死叉": { name:"死叉", english:"Death Cross", desc:"短期均线下穿长期均线，通常视为卖出信号。" },
  "市盈率": { name:"市盈率", english:"PE (Price-to-Earnings)", desc:"股价与每股收益的比值，反映市场对公司盈利的估值水平。" },
  "市净率": { name:"市净率", english:"PB (Price-to-Book)", desc:"股价与每股净资产的比值，衡量公司资产价值。" },
  "净资产收益率": { name:"净资产收益率", english:"ROE (Return on Equity)", desc:"净利润与平均股东权益的比值，衡量公司盈利能力。" },
  "换手率": { name:"换手率", english:"Turnover Rate", desc:"一定时间内股票转手买卖的频率，反映市场活跃度。" },
  "成交量": { name:"成交量", english:"Volume", desc:"一定时间内成交的股票数量，反映市场交易活跃程度。" },
  "北向资金": { name:"北向资金", english:"Northbound Capital", desc:"通过沪股通和深股通进入A股的香港及外资资金，被视为\"聪明钱\"。" },
  "主力资金": { name:"主力资金", english:"Main Capital Flow", desc:"大额资金（单笔>500万）的流入流出情况，反映主力机构动向。" },
  "海龟交易法则": { name:"海龟交易法则", english:"Turtle Trading System", desc:"著名的趋势跟踪交易系统，基于N日突破入场、ATR动态止损。" },
  "网格交易": { name:"网格交易", english:"Grid Trading", desc:"固定价差区间反复买卖的策略，适合震荡市场。" },
  "动量策略": { name:"动量策略", english:"Momentum Strategy", desc:"买入近期涨幅最大的股票，认为强者恒强。" },
  "均值回归": { name:"均值回归", english:"Mean Reversion", desc:"价格偏离均值后倾向于回归，偏离越大回归概率越高。" },
  "止损": { name:"止损", english:"Stop Loss", desc:"当亏损达到预定比例时强制平仓，控制单笔交易最大损失。" },
  "止盈": { name:"止盈", english:"Take Profit", desc:"当盈利达到预定比例时部分或全部平仓，锁定利润。" },
  "仓位管理": { name:"仓位管理", english:"Position Sizing", desc:"决定每笔交易投入多少资金的管理策略，控制整体风险。" },
  "Alpha": { name:"Alpha", english:"Alpha", desc:"策略超越市场基准的超额收益，反映选股和择时能力。" },
  "Beta": { name:"Beta", english:"Beta", desc:"策略相对于市场基准的波动敏感度。Beta=1表示与市场同步波动。" },
  "回测": { name:"回测", english:"Backtesting", desc:"在历史数据上模拟运行策略，检验策略的有效性和稳健性。" },
  "过拟合": { name:"过拟合", english:"Overfitting", desc:"策略在历史数据上表现很好但在未来数据上表现差，因为过度适配了历史噪音。" },
};

export function getTerm(name) {
  return TERMS[name] || { name, english:"", desc:"暂无解释" };
}
